[project]
name = "readmegen"
version = "0.1.0"
description = "📝 Instantly generate beautiful README.md files from your terminal."
authors = [
    { name="Your Name", email="your.email@example.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "typer[all]",
    "rich"
]

[project.scripts]
readmegen = "readmegen.main:app"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
